site_name: SARAV Documentaion
site_url: https://parallel-ml.github.io/docs/
site_description: SARAV

nav:
    - Home: index.md
    - Getting Started:
        - Connecting to Raspberry Pi: getting-started/setting-up-pi.md
        - Setting Up Speaker and Mic: getting-started/speaker-mic.md
    - Cameras:
        - Using the PiCamera: camera/picamera.md
        - Webcam video/image: camera/webcam.md
    - IMU (GPS, Accelerometer):
        - GPS (Neo 6M GPS): imu/gps.md
        - IMU (Berry IMU): imu/imu.md
    - Vision System:
        - Character Recognition: vision/character.md
    - Speech Recognition:
        - Deepspeech: speech/deepspeech.md
        - Sphinx: speech/sphinx.md
        - Text to Speech: speech/text-to-speech.md
    - Mapping:
        - Lidar: mapping/lidar-slam.md
    - Visual SLAM:
        - Webcam Information: visual_slam/webcam-information.md
        - Installing Docker on the Raspberry Pi: visual_slam/installing-docker-on-pi.md
        - Live Streaming Raspberry Pi Video: visual_slam/live-streaming-pi-video.md
        - Camera Calibration: visual_slam/calibration.md
        - Running SLAM: visual_slam/running-slam.md
    - iRobot:
        - Keyboard Control: irobot/keyboard.md
        - Navigation with Lidar/Voice: irobot/navi_lidar_voice.md
    - Adhoc Network: adhoc/adhoc.md
    - FPGA: fpga/split-networks.md
    - ASPLOS 2018: asplos2018/real-time.md
    - People: people/people.md

theme: 'windmill-dark'
theme_dir: 'mkdocs-windmill-dark/mkdocs_windmill_dark'
